# input configuration file to the animation

experiment_info:
  hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/"
  intro_text: "This experiment features the Crosspod program split into six parts: the forwarding logic is kept on the switch, and the booster logic is offloaded to separate supporting devices, one for each booster function.  This is a long experiment. Feel free to use 'Next Event Button (>>|)' to quickly move to the next point of interest."

static_tags:
  - node: p0e0
    text: "The full Crosspod program is executed on this element, featuring all 3 boosters: FEC, MCD, HC."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

  - node: S2_1
    text: "FEC (Forward Error Correction) decoder."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

  - node: S2_2
    text: "Compresses header."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

  - node: S2_3
    text: "MCD Booster - provides in-network caching of memcached entries."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

  - node: S2_4
    text: "Header decompressor."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

  - node: S2_5
    text: "FEC (Forward Error Correction) encoder."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

  - node: p0h0
    text: "This is the source host."
    hyperlink: null

  - node: p1h0
    text: "This is the destination host."
    hyperlink: null

event_tags:
  - time: 6348
    node: p0e0
    text: "Header is compressed. We show this by changing the packet's colour from blue to pink."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

  - time: 16740
    node: S2_2
    text: "Header is decompressed. We show this by changing the packet's colour from pink back to blue."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

  - time: 8030086
    node: p0e0
    text: "An FEC encoder-generated parity packet (coloured silver) will be sent from p0e0 to p0a0."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

  - time: 13046449
    node: S2_1
    text: "The parity packet is used by FEC to decode the lost packet. This can be seen as an additional compressed packet being generated."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

  - time: 98639076
    node: S2_3
    text: "The cached entries reside at this device. The reply (orange packet) from p0a0 reduces pressure from the target Memcached server."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

graph:
  show: "n"
  x_div: 1000000
  x_label: "time (sec)"
  y_label: "# packets received at receiver"
  title: ""
  curve_info:
    - file_name: "graph_log1.txt"
      curve_color: "#ffff00"
      legend_text: ""
      curve_width: 1
      packet_target: 

    - file_name: "graph_log2.txt"
      curve_color: "#00ff40"
      legend_text: ""
      curve_width: 1
      packet_target: 


packet_legend:
  - type: "TCP p0h0->p1h0"
    color: "#0000ff"

  - type: "TCP p1h0->p0h0"
    color: "#ffff00"

  - type: "Compressed"
    color: "#ff00ff"

  - type: "MCD Request"
    color: "#0EF3E1"

  - type: "MCD Reply"
    color: "#61D612"

  - type: "MCD Cached"
    color: "#FF8A00"

  - type: "Parity"
    color: "#ffffff"

  - type: "ICMP Request"
    color: "#ff0000"

introduction:
  show: "no"             # choose ("yes", "no")
