# input configuration file to the animation

experiment_info:
  hyperlink: "https://flightplan.cis.upenn.edu/sigcse21"
  intro_text: "The experiment demonstrates the packet loss in case of lossy link in the network."
  animation_time: 94

static_tags:
  - node: p0h0
    text: "This is the source host."
    hyperlink: null

  - node: p1h0
    text: "This is the destination host."
    hyperlink: null

event_tags:
  - time: 6014599
    node: p0e0
    text: "This packet will be dropped in the lossy link."
    hyperlink: null


graph:
  show: "y"
  x_div: 1000000
  x_label: "time (sec)"
  y_label: "# packets received at receiver"
  title: "Lossy Network Simulation"
  curve_info:
    - file_name: "graph_log1.txt"
      curve_color: "#ffff00"
      legend_text: "Lossy Network"
      curve_width: 1
      packet_target: p1h0

    - file_name: "graph_log2.txt"
      curve_color: "#00ff40"
      legend_text: "Non Lossy Network"
      curve_width: 1
      packet_target: p1h0

slide_show:
  show: "no"

packet_legend:
  - type: "ICMP p0h0->p1h0"
    color: "#0000ff"

  - type: "ICMP p1h0->p0h0"
    color: "#ffff00"


introduction:
  show: "no"             # choose ("yes", "no")
 