# input configuration file to the animation

experiment_info:
  hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits3/ALV_bt/README.md"

static_tags:
  - node: p0h3
    text: "This is host that generates traffic."
    hyperlink: null

  - node: p3h2
    text: "This is the destination host for traffic"
    hyperlink: null

event_tags:
  - time: 1443
    node: p0e1
    text: "Unlike the Tunneled Traffic experiment, this packet will follow the normal (routed) path p0e1->p0a1->c3->p3a1 to reach its destination (p3h2)."
    hyperlink: "https://github.com/eniac/Flightplan/blob/master/Wharf/splits3/ALV_bt/ALV_bt.p4#L121"

graph:
  show: "n"
  x_div: 1000000
  x_label: "time (sec)"
  y_label: "# packets received at receiver"
  title: ""
  curve_info:
    - file_name: "graph_log1.txt"
      curve_color: "#ffff00"
      legend_text: ""
      curve_width: 1
      packet_target: 

    - file_name: "graph_log2.txt"
      curve_color: "#00ff40"
      legend_text: ""
      curve_width: 1
      packet_target: 

packet_legend:
  - type: "TCP p0h3->p3h2"
    color: "#0000ff"

  - type: "TCP p3h2->p0h3"
    color: "#ffff00"
