# input configuration file to the animation

experiment_info:
  hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/"
  intro_text: "This experiment demonstartes the Header Compressor (HC) booster. HC booster compresses and decompresses the packet headers"

static_tags:
  - node: p0e0
    text: "HC Booster - Header is compressed here."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

  - node: p0a0
    text: "Header is decompressed here."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

  - node: p0h0
    text: "This is the source host."
    hyperlink: null

  - node: p1h0
    text: "This is the destination host."
    hyperlink: null

event_tags:
  - time: 3962
    node: p0e0
    text: "header compression booster compresses header bytes. The packet turning from blue to pink shows that it is now a compressed packet."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

  - time: 7094
    node: p0a0
    text: "At p0e0 pink packet turns blue. This shows that the compressed packet has been decompressed now."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

graph:
  show: "y"
  x_div: 1000000
  x_label: "time (sec)"
  y_label: "# bytes passed through node"
  title: "HC Effectiveness"
  curve_info:
    - file_name: "graph_log1.txt"
      curve_color: "#ffff00"
      legend_text: "Before Header Compression"
      curve_width: 1
      packet_target: p1e0

    - file_name: "graph_log2.txt"
      curve_color: "#00ff40"
      legend_text: "After Header Compression"
      curve_width: 1
      packet_target: dropper


packet_legend:
  - type: "Compressed"
    color: "#ff00ff"

  - type: "Parity"
    color: "#ffffff"

  - type: "TCP p0h0->p1h0"
    color: "#0000ff"

  - type: "TCP p1h0->p0h0"
    color: "#ffff00"

introduction:
  show: "no"             # choose ("yes", "no")