# input configuration file to the animation

experiment_info:
  hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/"
  intro_text: "This experiment features the FEC booster mitigating the packet loss from a faulty link. Parity packets are added to the packet stream and used to recover lost data packets."
  animation_time: 716

static_tags:
  - node: p0e0
    text: "FEC encoding generates parity packets and sends them with data packets forwarded to p0a0."
    hyperlink: "https://www.github.com/eniac/Flightplan/blob/master/Wharf/splits/ALV_Complete/ALV_Complete.p4#L254"

  - node: p0a0
    text: "Lost packets are recovered with the help of parity packets here."
    hyperlink: "https://github.com/eniac/Flightplan/blob/master/Wharf/splits/ALV_Complete/ALV_Complete.p4#L185"

  - node: p0h0
    text: "This is the source host."
    hyperlink: null

  - node: p1h0
    text: "This is the destination host."
    hyperlink: null

event_tags:
  - time: 3008916
    node: p0e0
    text: "An FEC encoder-generated parity packet (coloured silver) will be sent from p0e0 to p0a0."
    hyperlink: "https://www.github.com/eniac/Flightplan/blob/master/Wharf/splits/ALV_Complete/ALV_Complete.p4#L254"

  - time: 13032597
    node: p0a0
    text: "p0a0 receives the parity packet. FEC recreates the lost packet. This can be seen as an additional blue packet moving out of p0a0."
    hyperlink: "https://github.com/eniac/Flightplan/blob/master/Wharf/splits/ALV_Complete/ALV_Complete.p4#L185"

graph:
  show: "y"
  x_div: 1000000
  x_label: "time (sec)"
  y_label: "# packets received at receiver"
  title: "FEC Effectiveness"
  curve_info:
    - file_name: "graph_log1.txt"
      curve_color: "#ffff00"
      legend_text: "No FEC"
      curve_width: 1
      packet_target: p1h0

    - file_name: "graph_log2.txt"
      curve_color: "#00ff40"
      legend_text: "With FEC (k=5, h=1)"
      curve_width: 1
      packet_target: p1h0

slide_show:
  show: "no"


packet_legend:
  - type: "Parity"
    color: "#ffffff"

  - type: "TCP p0h0->p1h0"
    color: "#0000ff"

  - type: "TCP p1h0->p0h0"
    color: "#ffff00"


introduction:
  show: "no"             # choose ("yes", "no")
  tag_2d:
    menu:
      heading: "Menu"
      detail: "The menu can be expanded and collapsed by clicking this button."

    next_event_button:
      heading: "Next Event"
      detail: "Clicking on this button will fast-forward the experiment until the next point of interest."

    time_slider:
      heading: "Time Slider"
      detail: "The slider shows the progress of the experiment over time."

    elapsed_time:
      heading: "Elapsed Time"
      detail: "This shows the elapsed time since the experiment's start."

    remaining_time:
      heading: "Remaining Time"
      detail: "This shows the remaining time for the experiment."

    speed_slider:
      heading: "Speed Slider"
      detail: "Use this to change the display speed of the experiment's visualization."

    graph:
      heading: "Graph"          # choose ("none", <heading string>)
      detail: "This shows relevant quantitative information from the experiment."

    packet_legend:
      heading: "Packet Legend"
      detail: "Packet color legend to identify packets in the visualization."

    info_code_button:
      heading: "Info + Code"
      detail: "For any experiment, click on 'Info + Code' to access background info and code."

  tag_3d:
    edge_switch:
      node: "none"
      heading: "Edge Switch"
      detail: "(p*e*) The Switch that is directly connected to the host is called edge switch."
    
    aggregation_switch:
      node: "none"        # choose ("none", <node name>)
      heading: "Aggregation Switch"
      detail: "(p*a*) These switches interconnect edge and core switches."

    core_switch:
      node: "none"
      heading: "Core Switch"
      detail: "(c*) Core switches interconnect aggregation switches."

    supporting_device:
      node: "none"        # choose ("none", <node name>)
      heading: "Supporting Device"
      detail: "A switch may offload part of its program to a supporting device such as this."

    link:
      node1: "none"       # choose ("none", <node name>)
      node2: "p0a1"
      heading: "Link"
      detail: "Links connect switches and host together."
    
    lossy_link:
      node1: "p0a0"         # choose ("none", <node name>)
      node2: "p0e0"         # choose ("none", <node name>)
      heading: "Lossy Link"
      detail: "Lossy Link may drop packets at random because of a hardware fault."

    static_tag_info:
      node: "p0a0"          # choose ("none", <node name>)
      heading: "Info Tags"
      detail: "Additional information can be obtained by clicking on red beacons such as this."

  tag_info:
    zoom_info: 
      detail: "3D model can be zoomed in and out using mouse scroll."

    rotation_info:
      detail: "Model can be rotated on its axis using mouse click and drag."

    experiment_info: 
      detail: "none"      # choose ("none", <detail of experiment>)

    outro:
      detail: "none"      # choose ("none", <outro>)