# input configuration file to the animation

experiment_info:
  hyperlink: "https://github.com/eniac/Flightplan/blob/master/Wharf/splits/ALV_Complete_2_FW/README.md"
  intro_text: "This demo will help you understand the tool's interface.\nRight after clicking the <color=#EC7011>START</color> button below, a tag will be shown on the screen. Tags will help describe what you are seeing on the screen."

static_tags:
  - node: D_FW_1
    text: "This is the firewall. It resides on the supporting device connected to the switch p1e1."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2_FW/ALV_FW_split2.p4"

  - node: "D_V2_1"
    text: "FEC decoder. MCD Booster - provides in-network caching of memcached entries. Header decompressor"
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_1/ALV_Complete_split2.p4"

  - node: "D_V2_2"
    text: "FEC encoder. Header compressor."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_1/ALV_Complete_split2.p4"

  - node: D_V3_1
    text: "FEC (Forward Error Correction) encoder."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split2.p4"

  - node: D_V3_2
    text: "FEC (Forward Error Correction) decoder."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split3.p4"

  - node: D_V3_3
    text: "Header Decompressor, if multiplexed link."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split4.p4"

  - node: D_V3_4
    text: "MCD Booster - provides in-network caching of memcached entries."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split5.p4"

  - node: D_V3_5
    text: "Header Compressor, if heading out on a multiplexed link."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split6.p4"

event_tags:
  - time: 8256
    node: D_FW_1
    text: "We start with 'positive tests'. This packet is allowed to continue its journey by the firewall."
    hyperlink: "https://github.com/eniac/Flightplan/blob/master/Wharf/splits/ALV_Complete_2_FW/ALV_FW_split2.p4#L160"

  - time: 120885
    node: p1e0
    text: "This node implements network functions that aren't important in this demo. You will see packets bouncing around its supporting devices."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split1.p4"

  - time: 716224
    node: D_FW_1
    text: "We now come to 'negative tests'. This packet will not be allowed through by the firewall."
    hyperlink: "https://github.com/eniac/Flightplan/blob/master/Wharf/splits/ALV_Complete_2_FW/ALV_FW_split2.p4#L175"

  - time: 413491
    node: "Yellow Curve"
    text: "This curve shows the progress of the positive test and firewall's success rate so far."
    hyperlink: ""

  - time: 4997492
    node: "Green Curve"
    text: "This curve shows the progress of the negative test and the firewall's success rate so far."
    hyperlink: null

graph:
  show: "y"
  x_div: 1
  x_label: "% test completed"
  y_label: "% success rate"
  title: "Firewall Effectiveness"
  curve_info:
    - file_name: "graph_log1.txt"
      curve_color: "#ffff00"
      legend_text: "Positive Test"
      curve_width: 1
      packet_target: D_FW_1

    - file_name: "graph_log2.txt"
      curve_color: "#00ff40"
      legend_text: "Negative Test"
      curve_width: 4
      packet_target: D_FW_1

packet_legend:
  - type: "TCP Packets"
    color: "#0000ff"

introduction:
  show: "yes"             # choose ("yes", "no")
  tag_2d:
    menu:
      heading: "Menu"
      detail: "The menu can be expanded and collapsed by clicking this button."

    next_event_button:
      heading: "Next Event"
      detail: "Clicking on this button will fast-forward the experiment until the next point of interest."

    time_slider:
      heading: "Time Slider"
      detail: "The slider shows the progress of the experiment over time."

    elapsed_time:
      heading: "Elapsed Time"
      detail: "This shows the elapsed time since the experiment's start."

    remaining_time:
      heading: "Remaining Time"
      detail: "This shows the remaining time for the experiment."

    speed_slider:
      heading: "Speed Slider"
      detail: "Use this to change the display speed of the experiment's visualization."

    graph:
      heading: "Graph"          # choose ("none", <heading string>)
      detail: "This shows relevant quantitative information from the experiment."

    packet_legend:
      heading: "Packet Legend"
      detail: "Packet color legend to identify packets in the visualization."

    info_code_button:
      heading: "Info + Code"
      detail: "For any experiment, click on 'Info + Code' to access background info and code."

  tag_3d:
    edge_switch:
      node: "p0e0"
      heading: "Edge Switch"
      detail: "(p*e*) The Switch that is directly connected to the host is called edge switch."
    
    aggregation_switch:
      node: "p0a1"        # choose ("none", <node name>)
      heading: "Aggregation Switch"
      detail: "(p*a*) These switches interconnect edge and core switches."

    core_switch:
      node: "c2"
      heading: "Core Switch"
      detail: "(c*) Core switches interconnect aggregation switches."

    supporting_device:
      node: "D_V2_1"      # choose ("none", <node name>)
      heading: "Supporting Device"
      detail: "A switch may offload part of its program to a supporting device such as this."

    link:
      node1: "c3"
      node2: "p0a1"
      heading: "Link"
      detail: "Links connect switches and host together."
    
    lossy_link:
      node1: "p0a0"         # choose ("none", <node name>)
      node2: "p0e0"         # choose ("none", <node name>)
      heading: "Lossy Link"
      detail: "Lossy Link may drop packets at random because of a hardware fault."

    static_tag_info:
      node: "D_FW_1"        # choose ("none", <node name>)
      heading: "Info Tags"
      detail: "Additional information can be obtained by clicking on red beacons such as this."

  tag_info:
    zoom_info: 
      detail: "3D model can be zoomed in and out using mouse scroll."

    rotation_info:
      detail: "Model can be rotated on its axis using mouse click and drag."

    experiment_info: 
      detail: "This experiment tests the firewall's effectiveness. The firewall part of the P4 program has been offloaded to Device D_FW_1. The experiment consists of both positive and negative tests. It starts with a series of positive tests -- i.e., involving packets that we expect the firewall to let through. This is followed by negative tests, where we expect the firewall to block packets."
