# input configuration file to the animation

experiment_info:
  hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_All/"

static_tags:
  - node: p0e0
    text: "FEC encoder and decoder. Header compressor and decompressor. MCD Booster - provides in-network caching of memcached entries."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

  - node: D_V2_1
    text: "FEC decoder. MCD Booster - provides in-network caching of memcached entries. Header decompressor."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_1/ALV_Complete_split2.p4"

  - node: D_V2_2
    text: "FEC encoder. MCD Booster - provides in-network caching of memcached entries. Header compressor."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_1/ALV_Complete_split2.p4"

  - node: S2
    text: "FEC (Forward Error Correction) decoder. Header decompressor. MCD Booster - provides in-network caching of memcached entries."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_1_hl3new/ALV_Complete_split2_hl3new.p4"

  - node: p1a0
    text: "FEC encoder and decoder. If multiplexed link, then header decompress. MCD Booster - provides in-network caching of memcached entries."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

  - node: S1
    text: "FEC (Forward Error Correction) encoder. Header compressor."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_1_hl3new/ALV_Complete_split2_hl3new.p4"

  - node: D_FW_1
    text: "This is the firewall. It resides on the supporting device connected to the switch p1e1."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2_FW/ALV_FW_split2.p4"

  - node: D_V3_1
    text: "FEC (Forward Error Correction) encoder."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split2.p4"

  - node: D_V3_2
    text: "FEC (Forward Error Correction) decoder."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split3.p4"

  - node: D_V3_3
    text: "Header decompressor, If multiplexed link."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split4.p4"

  - node: D_V3_4
    text: "MCD Booster - provides in-network caching of memcached entries."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split5.p4"

  - node: D_V3_5
    text: "Header Decompressor, if heading out on a multiplexed link."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split6.p4"

  - node: S2_1
    text: "FEC (Forward Error Correction) decoder."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

  - node: S2_2
    text: "Compresses header."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

  - node: S2_3
    text: "Header decompressor."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

  - node: S2_4
    text: "MCD Booster - provides in-network caching of memcached entries."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

  - node: S2_5
    text: "FEC (Forward Error Correction) encode, if heading out on a lossy link."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_2_hl3new/ALV_Complete_split2_hl3new_2.p4"

  - node: FPolS2
    text: "Offload device for p1a1 to make routing decision."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_split2/ALV_S2part2.p4"

  - node: p0h0
    text: "This is the source host."
    hyperlink: null

  - node: p1h0
    text: "This is the destination host."
    hyperlink: null

event_tags:
  - time: 8019053
    node: p0e0
    text: "Now silver colored parity packet will travel from p0e0 to p0a0."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

  - time: 13035743
    node: D_V2_1
    text: "p0a0 receives the parity packet. FEC retrieves the lost packet. This can be seen as aditional blue packet moving out of p0a0"
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_1/ALV_Complete_split2.p4"

  - time: 8029314
    node: S2
    text: "Now silver colored parity packet will travel from p0e0 to p0a0."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_1_hl3new/ALV_Complete_split2_hl3new.p4"

  - time: 13048252
    node: p1a0
    text: "p1a0 receives the parity packet. FEC retrieves the lost packet. This can be seen as aditional blue packet moving out of p1a0"
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

  - time: 8070301
    node: p1a0
    text: "Now silver colored parity packet will travel from p0e0 to p0a0."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

  - time: 13111909
    node: S1
    text: "S1 receives the parity packet. FEC retrieves the lost packet. This can be seen as aditional yellow packet moving out of S1"
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits2/ALV_Complete_1_hl3new/ALV_Complete_split2_hl3new.p4"

  - time: 8078902
    node: D_V2_1
    text: "Now silver colored parity packet will travel from p0e0 to p0a0."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_1/ALV_Complete_split2.p4"

  - time: 13124382
    node: p0e0
    text: "p0e0 receives the parity packet. FEC retrieves the lost packet. This can be seen as aditional yellow packet moving out of p0e0."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete/ALV_Complete.p4"

  - time: 98666932
    node: D_V2_1
    text: "The cached packets reside at p0a0. The orange packet reply from p0a0 offloads the target destination host and sends the cached copy of requested."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_1/ALV_Complete_split2.p4"

  - time: 4042553
    node: D_V3_2
    text: "Since this node got the wrong header in packet, it is now sending one additional pink colored feedback packet to p1e0."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split3.p4"

  - time: 4047033
    node: D_V3_3
    text: "Since this node got the wrong header in packet, it is now sending one additional pink colored feedback packet to p1e0."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split4.p4"

  - time: 4051702
    node: D_V3_4
    text: "Since this node got the wrong header in packet, it is now sending one additional pink colored feedback packet to p1e0."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split5.p4"

  - time: 4057027
    node: D_V3_5
    text: "Since this node got the wrong header in packet, it is now sending one additional pink colored feedback packet to p1e0."
    hyperlink: "https://www.github.com/eniac/Flightplan/tree/master/Wharf/splits/ALV_Complete_2/ALV_Complete_2_split6.p4"

graph:
  show: "n"
  x_div: 1000000
  x_label: "time (sec)"
  y_label: "# packets received at receiver"
  title: ""
  curve_info:
    - file_name: "graph_log1.txt"
      curve_color: "#ffff00"
      legend_text: ""
      curve_width: 1
      packet_target: 

    - file_name: "graph_log2.txt"
      curve_color: "#00ff40"
      legend_text: ""
      curve_width: 1
      packet_target: 


packet_legend:
  - type: "TCP p0h0->p1h0"
    color: "#0000ff"

  - type: "TCP p1h0->p0h0"
    color: "#ffff00"

  - type: "MCD Request"
    color: "#0EF3E1"

  - type: "MCD Reply"
    color: "#61D612"

  - type: "MCD Cached"
    color: "#FF8A00"

  - type: "Parity"
    color: "#ffffff"

  - type: "ICMP Request"
    color: "#ff0000"

  - type: "Feedback"
    color: "#EC119D"
      